#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#define BUFFER_SIZE 1024
#define AVAIL_BYTES BUFFER_SIZE * 8

int main(int argc, char *argv[]) {
  if (argc < 3) {
    printf("Usage:\n"
           "hdr <input_file> <name>\n");

    return 1;
  }

  char *filename = argv[1];
  char *name = argv[2];

  const char *head_template = "unsigned char %s[] = {";
  char *head = calloc(strlen(name) + strlen(head_template) + 1, sizeof(char));
  sprintf(head, head_template, name);

  if (access(filename, F_OK) != 0) {
    printf("File does not exist: `%s`\n", filename);
    return 1;
  }

  FILE *fp = fopen(filename, "r");
  if (fp == 0) {
    printf("Could not open: `%s`\n", filename);
    return 1;
  }

  char** hexagons = 0;

  uint32_t bytes_read = 0;

  char buffer[BUFFER_SIZE];
  uint32_t total_len = 0;
  while ((bytes_read = fread(buffer, sizeof(char), BUFFER_SIZE, fp)) != 0) {
    for (uint32_t i = 0; i < bytes_read; i++) {
      char v[128];
      sprintf(v, "0x%x", buffer[i]);
      total_len++;
      hexagons = (char**)realloc(hexagons, (total_len + 1) * sizeof(char*));
      hexagons[total_len-1] = strdup(v);
    }
  }

  fclose(fp);

  const char *foot_template = "long unsigned int %s_len = %d;";
  char *foot = calloc(strlen(name) + strlen(foot_template) + 128, sizeof(char));
  sprintf(foot, foot_template, name, total_len);

  if (head) {
    printf("%s\n", head);
    free(head);
  }
  if (hexagons) {
    for (int i = 0; i < total_len; i++) {
      if (!hexagons[i])
        continue;
      printf("%s", hexagons[i]);
      free(hexagons[i]);

      if (i < total_len - 1) {
        printf(",");
      }

      if ((i + 1) % 12 == 0) {
        printf("\n");
      }
    }

    printf(",0x0");

    free(hexagons);
  }
  printf("};\n");

  if (foot) {
    printf("%s\n", foot);
    free(foot);
  }

  printf("// Generated by hdr.\n");

  return 0;
}
